nav:
  - Главная: README.md
  - Классы: классы.md
  - Народы: народы.md
  - Фракции: фракции.md
  - Артефакты: артефакты.md
  - Бестиарий: bestiary/README.md
  - Правила: rules/README.md
  - Инструменты мастера: tools/README.md
  - Лор: lore/README.md
  - Религии: religions/README.md
