site_name: Хроники Этеры НРИ

nav:
  - Главная: README.md
  - Классы: classes/README.md
  - Народы: narody/README.md
  - Фракции: factions/README.md
  - Артефакты: artefacts/README.md
  - Бестиарий: bestiary/README.md
  - Правила: rules/README.md
  - Инструменты мастера: tools/README.md
  - Лор: lore/README.md
  - Религии: religions/README.md
  
theme:
  name: mkdocs
