site_name: Хроники Этеры

nav:
  - Главная: README.md
  - Классы: Классы/README.md
  - Народы: Народы/README.md
  - Фракции: Фракции/README.md
  - Артефакты: Артефакты/README.md
  - Бестиарий: Бестиарий/README.md
  - Правила: Правила/README.md
  - Инструменты мастера: Ннструменты_мастера/README.md
  - Лор и история: Лор/README.md
  - Религии: Религии/README.md
